Snippy.Web/Models/ViewModels/SnippetViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    using System.Collections.Generic;

    public class SnippetViewModel : SnippetMinifiedViewModel
    {
        public IEnumerable<LabelViewModel> Labels { get; set; }
    }
}

Snippy.Web/Controllers/CommentController.cs
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using AutoMapper.QueryableExtensions;
    using Microsoft.AspNet.Identity;
    using Models.BindingModels;
    using Models.ViewModels;
    using Snippy.Models;

    public class CommentController : BaseController
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CommentBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var snippet = this.Data.Snippets.Find(model.SnippetId);
                if (snippet == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid comment!");
                }

                string currentUserId = this.User.Identity.GetUserId();
                var comment = new Comment
                {
                    AuthorId = currentUserId,
                    SnippetId = snippet.Id,
                    CreatedOn = DateTime.Now,
                    Content = model.Content
                };

                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var commentViewModel = this.Data.Comments
                    .All()
                    .Where(x => x.Id == comment.Id)
                    .Project()
                    .To<CommentMinifiedViewModel>()
                    .FirstOrDefault();
                return this.PartialView("DisplayTemplates/CommentMinifiedViewModel", commentViewModel);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid comment!");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var commentToDel = this.Data.Comments.All()
                .Where(c => c.Id == id)
                .Project()
                .To<CommentViewModel>()
                .FirstOrDefault();

            return View(commentToDel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, int snippetId)
        {
            var commentToDel = this.Data.Comments.Find(id);
            if (commentToDel.AuthorId == this.HttpContext.User.Identity.GetUserId())
            {
                this.Data.Comments.Delete(id);
                this.Data.SaveChanges();
            }

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Snippy.Web/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using AutoMapper.QueryableExtensions;
    using Models.ViewModels;

    public class LanguageController : BaseController
    {
        // GET: Language
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllSnippets(int id)
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var snippets = this.Data
                .Snippets
                .All()
                .Where(s => s.LanguageId == id)
                .Project()
                .To<SnippetDetailedViewModel>()
                .FirstOrDefault();

            return this.View(snippets);
        }
    }
}

Snippy.Web/Controllers/SnippetController.cs
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using Models.ViewModels;

    public class SnippetController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var snippet = this.Data
                .Snippets
                .All()
                .Where(s => s.Id == id)
                .Project()
                .To<SnippetDetailedViewModel>()
                .FirstOrDefault();

            return View(snippet);
        }

        public ActionResult All()
        {
            var labels = this.Data
                .Snippets
                .All()
                .OrderByDescending(s => s.CreatedOn)
                .Project()
                .To<SnippetViewModel>();

            return View(labels);
        }
    }
}

Snippy.Web/Views/Snippet/All.cshtml
@using Snippy.Web.Models.ViewModels
@model IEnumerable<SnippetViewModel>

<div class="row">
    <h2>All snippets</h2>
    <div class="col-md-12">
        @Html.DisplayFor(m => m)
    </div>
</div>

Snippy.Web/Views/Snippet/Details.cshtml
@model Snippy.Web.Models.ViewModels.SnippetDetailedViewModel

<div class="main-container">
    <div class="container">
        @Html.ActionLink(@Model.LanguageName, "AllSnippets", "Language", routeValues: new {id = @Model.Id, area = ""}, htmlAttributes: new {@class = "btn btn-success btn"})
        <span class="main-title">@Model.Title</span>
    </div>
    <div class="top-space col-md-12">
        <span class="glyphicon glyphicon-user"></span>
        <strong>@Model.AuthorName</strong>
        <span>on @Model.CreatedOn</span>
        <div>
            <span>Labels:</span>
            @Html.DisplayFor(m => m.Labels)
        </div>
    </div>
    <div>
        <p>@Model.Description</p>
        <div class="panel-default">
            <pre>@Model.Code</pre>
        </div>
    </div>
    <div>
        <h3>Comments:</h3>
        @if (User.Identity.IsAuthenticated)
        {
            using (Ajax.BeginForm("Add", "Comment", new {snippetId = @Model.Id}, new AjaxOptions()
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.InsertBefore,
                UpdateTargetId = "comments",
                OnSuccess = "onAddCommentSuccess",
                OnFailure = "onAddCommentFailure"
            }, new {@class = "form-group"}))
            {
                @Html.AntiForgeryToken()
                <textarea rows="3" cols="300" id="comment-input" name="Content" width="700px" class=""></textarea>
                <br/>
                <input type="submit" name="name" value="Add comment" class="btn btn-primary"/>
                <div id="add-comment-messages"></div>
            }
        }

        @if (Model.Comments.Any())
        {
            <div id="comments">
                @Html.DisplayFor(m => m.Comments)
            </div>
        }
        else
        {
            <div class="no-comments">
                <p>There are no comments right now.</p>
            </div>
        }
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        function onAddCommentSuccess() {
            var commentsWrapper = document.querySelector('#comments #nocomments');
            if (commentsWrapper) {
                commentsWrapper.removeChild(document.getElementById('no-comments'));
            }
            var addCommentMessageWrapper = document.getElementById("add-comment-messages");
            addCommentMessageWrapper.innerHTML = "You successfully added comment";
            setTimeout(function () {
                addCommentMessageWrapper.innerHTML = '';
            }, 1500);
        }
    </script>
}