Snippy.Web/Models/ViewModels/CommentMinifiedViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    using System;
    using System.Web;
    using AutoMapper;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Snippy.Models;

    public class CommentMinifiedViewModel : IMapFrom<Comment>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Content { get; set; }

        public string AuthorName { get; set; }

        public DateTime CreatedOn { get; set; }

        public bool CanDelete { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Comment, CommentMinifiedViewModel>()
                .ForMember(n => n.AuthorName, opt => opt.MapFrom(n => n.Author.UserName))
                .ForMember(n => n.CanDelete, opt => opt.MapFrom(n => n.Author.UserName == HttpContext.Current.User.Identity.Name));
        }
    }
}

Snippy.Web/Models/ViewModels/CommentViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    public class CommentViewModel : CommentMinifiedViewModel
    {
        public SnippetMinifiedViewModel Snippet { get; set; }
    }
}

Snippy.Web/Models/ViewModels/LabelViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    using Infrastructure;
    using Snippy.Models;

    public class LabelViewModel : IMapFrom<Label>
    {
        public int Id { get; set; }

        public string Text { get; set; }
    }
}

Snippy.Web/Models/ViewModels/LabelsMinifiedViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    using AutoMapper;
    using Infrastructure;
    using Snippy.Models;

    public class LabelsMinifiedViewModel : LabelViewModel, IHaveCustomMappings
    {
        public int SnippetsCount { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Label, LabelsMinifiedViewModel>()
                .ForMember(s => s.SnippetsCount, opt => opt.MapFrom(s => s.Snippets.Count));
        }
    }
}

Snippy.Web/Models/ViewModels/SnippetViewModel.cs
namespace Snippy.Web.Models.ViewModels
{
    using System.Collections.Generic;

    public class SnippetViewModel : SnippetMinifiedViewModel
    {
        public IEnumerable<LabelViewModel> Labels { get; set; }
    }
}

Snippy.Web/Controllers/CommentController.cs
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Net;
    using AutoMapper.QueryableExtensions;
    using Microsoft.AspNet.Identity;
    using Models.BindingModels;
    using Models.ViewModels;
    using Snippy.Models;

    public class CommentController : BaseController
    {
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CommentBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var snippet = this.Data.Snippets.Find(model.SnippetId);
                if (snippet == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid comment!");
                }

                string currentUserId = this.User.Identity.GetUserId();
                var comment = new Comment
                {
                    AuthorId = currentUserId,
                    SnippetId = snippet.Id,
                    CreatedOn = DateTime.Now,
                    Content = model.Content
                };

                this.Data.Comments.Add(comment);
                this.Data.SaveChanges();

                var commentViewModel = this.Data.Comments
                    .All()
                    .Where(x => x.Id == comment.Id)
                    .Project()
                    .To<CommentMinifiedViewModel>()
                    .FirstOrDefault();
                return this.PartialView("DisplayTemplates/CommentMinifiedViewModel", commentViewModel);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid comment!");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var commentToDel = this.Data.Comments.All()
                .Where(c => c.Id == id)
                .Project()
                .To<CommentViewModel>()
                .FirstOrDefault();

            return View(commentToDel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, int snippetId)
        {
            var commentToDel = this.Data.Comments.Find(id);
            if (commentToDel.AuthorId == this.HttpContext.User.Identity.GetUserId())
            {
                this.Data.Comments.Delete(id);
                this.Data.SaveChanges();
            }

            return this.RedirectToAction("Index", "Home");
        }
    }
}

Snippy.Web/Controllers/LabelController.cs
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using Models.ViewModels;

    public class LabelController : BaseController
    {
        // GET: Label
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var label = this.Data
                .Labels
                .All()
                .Where(l => l.Id == id)
                .Project()
                .To<LabelDetailedViewModel>()
                .FirstOrDefault();

            return this.View(label);
        }
    }
}

Snippy.Web/Controllers/SnippetController.cs
using System.Web.Mvc;

namespace Snippy.Web.Controllers
{
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using Models.ViewModels;

    public class SnippetController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var snippet = this.Data
                .Snippets
                .All()
                .Where(s => s.Id == id)
                .Project()
                .To<SnippetDetailedViewModel>()
                .FirstOrDefault();

            return View(snippet);
        }

        public ActionResult All()
        {
            var labels = this.Data
                .Snippets
                .All()
                .OrderByDescending(s => s.CreatedOn)
                .Project()
                .To<SnippetViewModel>();

            return View(labels);
        }
    }
}

Snippy.Web/Views/Shared/DisplayTemplates/CommentMinifiedViewModel.cshtml
@using Microsoft.AspNet.Identity
@model Snippy.Web.Models.ViewModels.CommentMinifiedViewModel

<div class="panel panel-default">
    <div class="panel-heading">
        @if (@Model.CanDelete)
        {
            <span class="pull-right">
                @Html.ActionLink("X", "Delete", "Comment", routeValues: new { id = Model.Id }, htmlAttributes: new { @title = "Delete photo?" })
            </span>
        }
        <p>@Model.Content</p>
        <span class="glyphicon glyphicon-user"></span>
        <strong>@Model.AuthorName</strong>
        <span>on @Model.CreatedOn</span>
    </div>
</div>

Snippy.Web/Views/Shared/DisplayTemplates/CommentViewModel.cshtml
@model Snippy.Web.Models.ViewModels.CommentViewModel

<div class="panel panel-default">
    <div class="panel-heading">
        <p>@Model.Content</p>
        <span class="glyphicon glyphicon-user"></span>
        <strong>@Model.AuthorName</strong>
        <span>on @Model.CreatedOn</span>
        <div>
            <span>on snippet</span>
            @Html.ActionLink(@Model.Snippet.Title, "Details", "Snippet", new { id = Model.Snippet.Id, area = "" }, null)
        </div>
    </div>
</div>

Snippy.Web/Views/Shared/DisplayTemplates/LabelViewModel.cshtml
@model Snippy.Web.Models.ViewModels.LabelViewModel

@Html.ActionLink(@Model.Text, "Details", "Label", routeValues: new { id = @Model.Id, area = "" }, htmlAttributes: new { @class = "btn btn-primary btn-sm" })

Snippy.Web/Views/Shared/DisplayTemplates/LabelsMinifiedViewModel.cshtml
@model Snippy.Web.Models.ViewModels.LabelsMinifiedViewModel

<li class="list-group-item">
    <span class="badge">@Model.SnippetsCount</span>
    @Html.ActionLink(@Model.Text, "Details", "Label", new { id = Model.Id, area = "" }, null)
</li>

Snippy.Web/Views/Shared/DisplayTemplates/SnippetViewModel.cshtml
@model Snippy.Web.Models.ViewModels.SnippetViewModel

<div>
    <h4>
        @Html.ActionLink(@Model.Title, "Details", "Snippet", new {id = Model.Id, area = ""}, null)
    </h4>
    @Html.DisplayFor(m => m.Labels)
</div>